// frontend/src/Components/Login.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import "./Login.css";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import axios from "axios";
import { apiUrl } from "../apiconfig";

function Login() {
  const navigate = useNavigate();
  const {
    register,
    handleSubmit,
    setError,
    formState: { errors },
  } = useForm();


  useEffect(() => {

    localStorage.clear();

  }, []);
  const onSubmit = async (formData) => {
    try {
      const response = await axios.post(
        apiUrl+"/api/auth/login",
        formData
      );
if(response.status==200)
{

if(response.data.message=="Invalid Credentials")
{
  setError("password", {
    type: "manual",
    message: "Invalid Email or Password",
  });
}
else{
  
  const user = response.data;
  console.log("response.data",response.data);
  localStorage.setItem("token", response.data.token);

  let userData = {
    role: user.role,
    userId: user.userId,
    userName: user.firstName + " " + user.lastName,
  };

  localStorage.setItem("userData", JSON.stringify(userData));
  if (user.role == "seller") {
    navigate("/userproducts");
  } else {
    navigate("/productlist");
  }
}


}

    } catch (error) {
      // navigate("/error");
    }
  };

  return (
    <div className="login-container">
    <div className="login-wrapper">
      <div className="login-left">
        <div className="login-box">
          <h2>Login</h2>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="form-group">
              <input
                type="text"
                name="email"
                placeholder="Email"
                {...register("email", {
                  required: "Email is required",
                  pattern: {
                    value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                    message: "Invalid email address",
                  },
                })}
              />
              {errors.email && (
                <div className="error">{errors.email.message}</div>
              )}
            </div>
            <div className="form-group">
              <input
                type="password"
                name="password"
                placeholder="Password"
                {...register("password", {
                  required: "Password is required",
                  minLength: {
                    value: 6,
                    message: "Password must be at least 6 characters",
                  },
                })}
              />
              {errors.password && (
                <div className="error">{errors.password.message}</div>
              )}
            </div>
            <button type="submit" className="login-button">
              Login
            </button>
          </form>
          <div className="signup-link">
            Don't have an account? <Link to="/register">Signup</Link>
          </div>
        </div>
      </div>
      <div className="login-right">
       <h1>Recipe</h1>
       <h1>Connect</h1>
       <h4>Find Your recipe</h4>
     </div>
    </div>
  </div>
  );
}

export default Login;

// recipeconnet/angualrapp/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  submitted = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.pattern(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  ngOnInit(): void {
    localStorage.clear();
  }

  onSubmit() {
    this.submitted = true;
    if (this.loginForm.valid) {
      this.authService.login(this.loginForm.value)
        .subscribe(
          
          (response: any) => {
            console.log(response);
            if (response.status === 200) {

              if (response.body.message === "Invalid Credentials") {
                let passwordControl = this.loginForm.get('password');
                if (passwordControl) {
                  passwordControl.setErrors({ 'manual': 'Invalid Email or Password' });
                }
              } else {
                const user = response.body;
                console.log("response.data", response.body);
                localStorage.setItem("token", response.body.token);

                const userData = {
                  role: user.role,
                  userId: user.userId,
                  userName: user.username,
                };



                localStorage.setItem("userData", JSON.stringify(userData));

                if (user.role === "seller") {
                  this.router.navigate(['/usertask']);
                } else {
                  this.router.navigate(['/displaytask']);
                }
              }
            }
          },
          (error) => {
            this.router.navigate(['/error']);
          }
        );
    }
  }
}

<div class="login-container">
  <div class="login-wrapper">
    <div class="login-left">
      <div class="login-box">
        <h2>Login</h2>
        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
          <div class="form-group">
            <input type="text" formControlName="email" placeholder="Email" />
            <div class="error" *ngIf="submitted && loginForm.get('email')?.hasError('required')">
              Email is required
            </div>
            <div class="error" *ngIf="submitted && loginForm.get('email')?.hasError('pattern')">
              Invalid email address
            </div>
          </div>
          <div class="form-group">
            <input type="password" formControlName="password" placeholder="Password" />
            <div class="error" *ngIf="submitted && loginForm.get('password')?.hasError('required')">
              Password is required
            </div>
            <div class="error" *ngIf="submitted && loginForm.get('password')?.hasError('minlength')">
              Password must be at least 6 characters
            </div>
            <div class="error" *ngIf="submitted && loginForm.get('password')?.hasError('manual')">
              {{ loginForm.get('password')?.getError('manual') }}
            </div>
          </div>
          <button type="submit" class="login-button">Login</button>
        </form>
        <div class="signup-link">
          Don't have an account? <a routerLink="/register">Signup</a>
        </div>
      </div>
    </div>
    <div class="login-right">
      <h1>Recipe</h1>
      <h1>Connect</h1>
      <h4>Find Your recipe</h4>
    </div>
  </div>
</div>


https://github.com/dhayananthdevaraj/recipeconnect.git
